development:
  adapter: postgresql
  encoding: utf8
  database: raffle_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: raffle_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: raffle_production
  pool: 5
  username: 
  password:
